// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_grabbed40 = "CgkI7MnvjvEOEAIQBA"; // <GPGSID>
        public const string achievement_mastergrabber = "CgkI7MnvjvEOEAIQCg"; // <GPGSID>
        public const string achievement_grabbed70 = "CgkI7MnvjvEOEAIQBw"; // <GPGSID>
        public const string achievement_fruity = "CgkI7MnvjvEOEAIQCw"; // <GPGSID>
        public const string leaderboard_highscore = "CgkI7MnvjvEOEAIQDQ"; // <GPGSID>
        public const string leaderboard_money = "CgkI7MnvjvEOEAIQDg"; // <GPGSID>
        public const string achievement_grabbed90 = "CgkI7MnvjvEOEAIQCQ"; // <GPGSID>
        public const string achievement_completionist = "CgkI7MnvjvEOEAIQDA"; // <GPGSID>
        public const string achievement_grabbed30 = "CgkI7MnvjvEOEAIQAw"; // <GPGSID>
        public const string achievement_grabbed20 = "CgkI7MnvjvEOEAIQAg"; // <GPGSID>
        public const string achievement_grabbed50 = "CgkI7MnvjvEOEAIQBQ"; // <GPGSID>
        public const string achievement_grabbed60 = "CgkI7MnvjvEOEAIQBg"; // <GPGSID>
        public const string achievement_grabbed80 = "CgkI7MnvjvEOEAIQCA"; // <GPGSID>
        public const string achievement_grabbed10 = "CgkI7MnvjvEOEAIQAQ"; // <GPGSID>

}

